---
title: "homework"
output:
  html_document:
    keep_md: true
date: '2022-06-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(dplyr)
library(ggplot2)
library(nycflights13)


library(tidyverse)

```{r}
library(dplyr)
library(ggplot2)
library(nycflights13)
library(tidyverse)
```


```{r}
filter(flights, month == 1, day == 1)
```
```{r}
jan1 <- filter(flights, month == 1, day == 1)

(dec25 <- filter(flights, month == 12, day == 25))

filter(flights, month == 1)
sqrt(2) ^ 2 == 2
1/49*49==1

near(sqrt(2) ^ 2, 2) # 무한자리수는 == 대신 near()사용
near(1/ 49*49,1)
```


```{r}
#11월 또는 12월에 출발한 모든 항공편
filter(flights, month == 11 | month == 12)
# x %in% y = x 이거나 y인 모든 행을 선택
nov_dec <- filter(flights, month %in% c(11, 12))
```




```{r}
#도착 또는 출발 시 2시간 이상 지연되지 않은 항공편 찾기
filter(flights, !(arr_delay > 120 | dep_delay > 120))
filter(flights, arr_delay <= 120, dep_delay <= 120)
```


```{r}
###NA값
###비교를 어렵게 하는 NA
###값의 누락여부 확인
x <- NA
y <- NA
is.na(x)
###filter() -> 조건이 TRUE인 행만 포함
### FALSE 및 NA값 제외
df <- tibble(x = c(1, NA, 3))
filter(df, x >1)
filter(df, is.na(x)|x>1)

```









